DIR  := app
BIN  := lzz3
LIBS := cpp output config util
# DL defined in make.$CONFIG
MORELIBS = basil$(OPTSUFFIX) lua $(DL)
MORELIBDIRS = $(BASILLIBDIR)
INCDIRS = $(BASILSRCDIR)
include $(MAKETOOLS)/make.include
