DIR  := app
BIN  := lzz3
LIBS := cpp output config util
# DL defined in make.$CONFIG
MORELIBS = basil$(OPTSUFFIX) lua $(DL)
MORELIBDIRS = $(BASILCC_LIB)
INCDIRS = $(BASILCC_SRC)
include $(MAKETOOLS)/make.include
